apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../library/azure-pipelines/_global/
  - ../../../library/azure-pipelines/azure-pipelines-agent/
  - akvs-azure-pipelines-agent-pat-token.yaml
patchesStrategicMerge:
  - patch-helmrelease-azure-pipelines-agent.yaml
